### ISSUE TITLE
discussion about the new datascource config format at etc-bpview-datascource

### ISSUE THREAD

**Issue by PetziAt** [BPView/BPView#27]
"UNIQUE NAME": # name must be unique !!!
  provider: icinga # nagios # scom
  provider-source: ido

  icinga:
    ido:
      host: heimdall.dc.ovido.at
      port: 3306
      some: thing
    mk-livestatus:
      socket: /var/spool/icinga/rw/live
      some: thing

  scom:
    mssql:
      host: mssql.database.host
      some: thing

**Comment by scrat14** [comment]
New format:

Default is the default value in case a business process doesn't have one of the providers configured.

>default:
>  source: icinga-ido 


Each backend block requires a provider section which defines the type (e.g. mk-livestatus or ido)

>icinga-ido:
>  provider: ido
>  host: 127.0.0.1 
>  port: 3306
>  type: mysql
>  database: icinga
>  username: icinga
>  password: icinga
>  prefix: icinga_
>  timeout: 10
>  cache_time: 30
>  cache_file: "/dev/shm/bpview_icinga_cache"

>mk-livestatus:
>  provider: mk-livestatus
>  socket: /var/spool/icinga/rw/live  
>  cache_time: 30
>  cache_file: "/dev/shm/bpview_mklivestatus_cache"

Each business process needs a new attribute PROVIDER which must match with one of the blocks in datasource.yml. If PROVIDER is missing we use the default provider.

>evn-topic-product:
>  BP:
>    NAME: "product"
>    DESC: "Business Process"
>    TYPE: and
>    DISP: 0
>    MIND: 0
>    PROVIDER: "icinga-ido"
